### ISSUE TITLE
ImportError for `datashader.bokeh_ext` after upgrading Bokeh to 12.10

### ISSUE THREAD

**Issue by esvhd** [bokeh/datashader#507]
Hi

Looks like after upgrading to `Bokeh` 12.10, `datashader` 0.6.1 is seeing some dependency issues with the following case. I'm assuming this would be something for the next update? Or am I missing something here? 
Thanks.

```python
In [1]: import bokeh 

In [2]: bokeh.__version__
Out[2]: '0.12.10'

In [3]: import datashader.bokeh_ext
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-50bd50116ce8> in <module>()
----> 1 import datashader.bokeh_ext

/usr/anaconda3/lib/python3.6/site-packages/datashader/bokeh_ext.py in <module>()
      6 import numpy as np
      7 
----> 8 from bokeh.io import notebook_div
      9 from bokeh.document import Document
     10 from bokeh.models import (CustomJS, ColumnDataSource, Square, HoverTool,

ImportError: cannot import name 'notebook_div'

In [4]: import datashader as ds

In [5]: ds.__version__
Out[5]: '0.6.1'
```

**Comment by esvhd** [comment]
Sorry looks like this might have been fixed in master.. Great job guys.

**Comment by jbednar** [comment]
Yes, should be fixed in master, but we should also have a release out by now to avoid people having this problem!  Should arrive *very* soon now; still trying to fix one more bug...
